/* LAYOUT */
export const GET_PRODUCT_SOLD_LIST = 'GET_PRODUCT_SOLD_LIST';
export const GET_PRODUCT_SOLD_LIST_SUCCESS = 'GET_PRODUCT_SOLD_LIST_SUCCESS';
export const GET_PRODUCT_SOLD_DETAIL = 'GET_PRODUCT_SOLD_DETAIL';
export const GET_PRODUCT_SOLD_DETAIL_SUCCESS = 'GET_PRODUCT_SOLD_DETAIL_SUCCESS';
export const CREATE_PRODUCT_SOLD = 'CREATE_PRODUCT_SOLD';
export const CREATE_PRODUCT_SOLD_SUCCESS = 'CREATE_PRODUCT_SOLD_SUCCESS';
export const RESET_ACTION_SUCCESS = 'RESET_ACTION_SUCCESS';
export const DELETE_PRODUCT_SOLD = 'DELETE_PRODUCT_SOLD';
export const DELETE_PRODUCT_SOLD_SUCCESS = 'DELETE_PRODUCT_SOLD_SUCCESS';
export const UPDATE_PRODUCT_SOLD = 'UPDATE_PRODUCT_SOLD';
export const UPDATE_PRODUCT_SOLD_SUCCESS = 'UPDATE_PRODUCT_SOLD_SUCCESS';
export const RESET_PRODUCT_SOLD_DETAIL = 'RESET_PRODUCT_SOLD_DETAIL';

