/* LAYOUT */
export const GET_MY_WAREHOUSE_LIST = 'GET_MY_WAREHOUSE_LIST';
export const GET_MY_WAREHOUSE_LIST_SUCCESS = 'GET_MY_WAREHOUSE_LIST_SUCCESS';
export const GET_MY_WAREHOUSE_DETAIL = 'GET_MY_WAREHOUSE_DETAIL';
export const GET_MY_WAREHOUSE_DETAIL_SUCCESS = 'GET_MY_WAREHOUSE_DETAIL_SUCCESS';
export const CREATE_PRODUCT_FOR_WAREHOUSE = 'CREATE_PRODUCT_FOR_WAREHOUSE';
export const CREATE_PRODUCT_FOR_WAREHOUSE_SUCCESS = 'CREATE_PRODUCT_FOR_WAREHOUSE_SUCCESS';
export const RESET_ACTION_SUCCESS = 'RESET_ACTION_SUCCESS';
export const DELETE_PRODUCT_WAREHOUSE = 'DELETE_PRODUCT_WAREHOUSE';
export const DELETE_PRODUCT_WAREHOUSE_SUCCESS = 'DELETE_PRODUCT_WAREHOUSE_SUCCESS';
export const UPDATE_PRODUCT_WAREHOUSE = 'UPDATE_PRODUCT_WAREHOUSE';
export const UPDATE_PRODUCT_WAREHOUSE_SUCCESS = 'UPDATE_PRODUCT_WAREHOUSE_SUCCESS';
export const RESET_MY_WAREHOUSE_DETAIL = 'RESET_MY_WAREHOUSE_DETAIL';

