/* LAYOUT */
export const GET_COST_TYPE = 'GET_COST_TYPE';
export const GET_COST_TYPE_SUCCESS = 'GET_COST_TYPE_SUCCESS';
export const CREATE_COST_TYPE = 'CREATE_COST_TYPE';
export const CREATE_COST_TYPE_SUCCESS = 'CREATE_COST_TYPE_SUCCESS';
export const RESET_ACTION_SUCCESS = 'RESET_ACTION_SUCCESS';
export const DELETE_COST_TYPE = 'DELETE_COST_TYPE';
export const DELETE_COST_TYPE_SUCCESS = 'DELETE_COST_TYPE_SUCCESS';
export const UPDATE_COST_TYPE = 'UPDATE_COST_TYPE';
export const UPDATE_COST_TYPE_SUCCESS = 'UPDATE_COST_TYPE_SUCCESS';
