/* LAYOUT */
export const GET_PRODUCTS_TYPE = 'GET_PRODUCTS_TYPE';
export const GET_PRODUCTS_TYPE_SUCCESS = 'GET_PRODUCTS_TYPE_SUCCESS';
export const CREATE_PRODUCT_TYPE = 'CREATE_PRODUCT_TYPE';
export const CREATE_PRODUCT_TYPE_SUCCESS = 'CREATE_PRODUCT_TYPE_SUCCESS';
export const RESET_ACTION_SUCCESS = 'RESET_ACTION_SUCCESS';
export const DELETE_PRODUCT_TYPE = 'DELETE_PRODUCT_TYPE';
export const DELETE_PRODUCT_TYPE_SUCCESS = 'DELETE_PRODUCT_TYPE_SUCCESS';
export const UPDATE_PRODUCT_TYPE = 'UPDATE_PRODUCT_TYPE';
export const UPDATE_PRODUCT_TYPE_SUCCESS = 'UPDATE_PRODUCT_TYPE_SUCCESS';
