/* LAYOUT */
export const GET_COST_INCURRED = 'GET_COST_INCURRED';
export const GET_COST_INCURRED_SUCCESS = 'GET_COST_INCURRED_SUCCESS';
export const CREATE_COST_INCURRED = 'CREATE_COST_INCURRED';
export const CREATE_COST_INCURRED_SUCCESS = 'CREATE_COST_INCURRED_SUCCESS';
export const RESET_ACTION_SUCCESS = 'RESET_ACTION_SUCCESS';
export const DELETE_COST_INCURRED = 'DELETE_COST_INCURRED';
export const DELETE_COST_INCURRED_SUCCESS = 'DELETE_COST_INCURRED_SUCCESS';
export const UPDATE_COST_INCURRED = 'UPDATE_COST_INCURRED';
export const UPDATE_COST_INCURRED_SUCCESS = 'UPDATE_COST_INCURRED_SUCCESS';
