/* LAYOUT */
export const GET_WAREHOUSE_LIST = 'GET_WAREHOUSE_LIST';
export const GET_WAREHOUSE_LIST_SUCCESS = 'GET_WAREHOUSE_LIST_SUCCESS';
export const CREATE_WAREHOUSE = 'CREATE_WAREHOUSE';
export const CREATE_WAREHOUSE_SUCCESS = 'CREATE_WAREHOUSE_SUCCESS';
export const RESET_ACTION_SUCCESS = 'RESET_ACTION_SUCCESS';
export const DELETE_WAREHOUSE = 'DELETE_WAREHOUSE';
export const DELETE_WAREHOUSE_SUCCESS = 'DELETE_WAREHOUSE_SUCCESS';
export const UPDATE_WAREHOUSE = 'UPDATE_WAREHOUSE';
export const UPDATE_WAREHOUSE_SUCCESS = 'UPDATE_WAREHOUSE_SUCCESS';
